#! /bin/bash

set -e # fail whole thing
set -o pipefail # fail pipes

export CONFIGNAME=gcc-debug

echo "Building local package"
make

echo "Building inet package"
pushd ../inet/src > /dev/null
make all
popd > /dev/null

echo "Starting simulation"
CSCI_566_proj_1 -c QuestionB -n .:../inet/src -l ../inet/src/INET | sed '/Could not load image/d'
